image:
    - Visual Studio 2015
environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
install:
    - "%PYTHON%\\python.exe -m pip install --upgrade setuptools pip"
    - "%PYTHON%\\python.exe -m pip install --upgrade virtualenv"
    - "%PYTHON%\\python.exe -m pip install --upgrade flake8 pylint"
    - "%PYTHON%\\python.exe -m pip --version"
    - "%PYTHON%\\python.exe -m virtualenv --version"
    - "%PYTHON%\\python.exe -m flake8 --version"
    - "%PYTHON%\\python.exe -m pylint --version"
    - "git --version"
    - "%PYTHON%\\python.exe -m pip install pytest pytest-cov codecov"
build: off
test_script:
    - "%PYTHON%\\python.exe -m flake8 --count %APPVEYOR_BUILD_FOLDER%"
    - "%PYTHON%\\python.exe -m pylint %APPVEYOR_BUILD_FOLDER%"
    - "%PYTHON%\\python.exe -m pytest lithium\\tests.py -v --cov . --cov-report term-missing"
on_success:
    - "%PYTHON%\\python.exe -m codecov"
skip_branch_with_pr: true
