dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install pytest-cov codecov
script:
    - py.test lithium/tests.py -v --cov . --cov-report term-missing
after_success:
    - codecov
